### ISSUE TITLE
updated deps for google-closure-compiler ?

### ISSUE THREAD

**Issue by mreinstein** [ampproject/rollup-plugin-closure-compiler#218]
@kristoferbaxter  thanks for maintaining this package! Wondering if we could please get a new release that bumps the google closure compiler dependency? there are some recent things it added that I need to avoid breaking my code.

**Comment by kristoferbaxter** [comment]
Resolved with `0.11.0`! Thanks for your patience.

**Comment by mreinstein** [comment]
thanks for continuing to maintain, brother!
