### ISSUE TITLE
Strip redundant semicolons

### ISSUE THREAD

**Issue by JoviDeCroock** [ampproject/rollup-plugin-closure-compiler#318]
## Is your feature request related to a problem? Please describe.

When comparing terser to this I found out that one of the differences is that terser strips away the semicolons

```
input: 
(async function() {
	console.log('foo');
})();

terser: try{console.log("foo")}catch(o){Promise.reject(o)}
closure: try{console.log("foo")}catch(a){Promise.reject(a)};
```

## Describe the solution you'd like

Maybe we can solve this by having a postprocessing step where these are stripped away

**Comment by kristoferbaxter** [comment]
Resolved with #321.
