### ISSUE TITLE
UnhandledPromiseRejectionWarning: SyntaxError: Duplicate export

### ISSUE THREAD

**Issue by bluebill1049** [ampproject/rollup-plugin-closure-compiler#333]
Hi, 

Thanks for this awesome rollup plugin and your hard work.

I have would like to use this plugin for this lib that i am working on: 
https://github.com/react-hook-form/react-hook-form

I did encounter an issue with the plugin and the error log is below: 
<img width="827" alt="Screen Shot 2020-02-28 at 7 42 00 pm" src="https://user-images.githubusercontent.com/10513364/75524635-6837be80-5a62-11ea-87df-a1e7aab5b6a9.png">

(useForm as duplicated export is not the root cause as the file only have a single export)

and here is my rollup config:

```
import typescript from 'rollup-plugin-typescript2';
import compiler from '@ampproject/rollup-plugin-closure-compiler';
import pkg from './package.json';

export function getConfig({
  tsconfig = './tsconfig.json',
  output = [
    {
      file: `dist/${pkg.name}.js`,
      format: 'cjs',
      exports: 'named',
    },
    {
      file: `dist/${pkg.name}.es.js`,
      format: 'esm',
    },
  ],
} = {}) {
  return {
    input: 'src/index.ts',
    external: ['react', 'react-dom'],
    plugins: [
      typescript({
        tsconfig,
        clean: true,
      }),
      compiler(),
    ],
    output,
  };
}

export default getConfig();
```

Here is the commit which i made for the config: 
https://github.com/react-hook-form/react-hook-form/commit/df7fb536234aa1dd13f6c77f7450bfc60b70b2ee

util i had the error above and reverted the commit.

Thanks for taking a look at this.

**Comment by kristoferbaxter** [comment]
Resolved with 0.23.0.

**Comment by bluebill1049** [comment]
wow thanks a lot @kristoferbaxter much appreciated your hard work.

**Comment by kristoferbaxter** [comment]
Happy to help!

**Comment by bluebill1049** [comment]
<img width="1102" alt="Screen Shot 2020-03-02 at 7 06 04 pm" src="https://user-images.githubusercontent.com/10513364/75656818-eb525200-5cb8-11ea-8b07-d2100d4db320.png">

sorry to report this, but looks like the latest is broken the bundle. rollup config is stay unchanged.
