### ISSUE TITLE
Add "include" and "exclude" options

### ISSUE THREAD

**Issue by egormalyutin** [ampproject/rollup-plugin-closure-compiler#347]
Hello! Can you add `include` and `exclude` options like in [rollup-plugin-terser](https://github.com/TrySound/rollup-plugin-terser)?

**Comment by TrySound** [comment]
I'm actually planning to drop include/exclude in favour of output plugins.

**Comment by egormalyutin** [comment]
@TrySound But how then I can repeat this functionality?

**Comment by TrySound** [comment]
Which functionality? Running terser on specific modules in output was the only reason I added this feature. Later rollup added output plugins which fully covered that reason too. include/exclude is error prone with generated names. Safer to just use output plugins.

**Comment by egormalyutin** [comment]
@TrySound Oh, I just didn't understand you. Thanks! :+1:

**Comment by MaxMilton** [comment]
It's worth noting that this plugin doesn't support being used as an output plugin because it uses a `buildStart` hook.

If running this plugin on specific output files is important to you, consider opening a new issue to support use as an output plugin.
