### ISSUE TITLE
Warnings are not logged even when setting warning_level to VERBOSE

### ISSUE THREAD

**Issue by philipwalton** [ampproject/rollup-plugin-closure-compiler#42]
## What's the issue?

If I set the closure compiler flag `warning_level` to `VERBOSE`, those warnings don't show up anywhere when using this plugin.

## How do we reproduce the issue?

Try to compile any code that should work but also produce a warning. For example:

```js
console.log(document.getElementById(1));
```

With `warning_level=VERBOSE`, I'd expect to see the following:

```
JSC_TYPE_MISMATCH: actual parameter 1 of Document.prototype.getElementById does not match formal parameter
found   : number
required: string at line 1 character 36
console.log(document.getElementById(1))
                                    ^
```

## Additional context

It seems like the problem occurs here: https://github.com/ampproject/rollup-plugin-closure-compiler/blob/0.6.1/src/compiler.ts#L57-L62

The plugin only errors if `exitCode` is not `0`, but then it doesn't do anything with `stdErr`, which is where the warnings are.

### Wish list

What would be *really* nice is if the plugin surfaced the warnings *and also* transformed the line/col numbers back to the original source files via the source maps. [I do something similar here](https://github.com/googleanalytics/autotrack/blob/master/bin/build.js#L83-L92), and it's super helpful when debugging.

**Comment by kristoferbaxter** [comment]
Quite interesting. 

Thank you for the bug report, I'll attempt to resolve this in the next week or so.

**Comment by MaxMilton** [comment]
I've run into this as well. During development I'd love to use settings like this:

```js
{
  compilation_level: 'ADVANCED',
  warning_level: 'VERBOSE',
  jscomp_warning: '*',
}
```

**Comment by kristoferbaxter** [comment]
Started a branch here: https://github.com/ampproject/rollup-plugin-closure-compiler/tree/error-reporting

Initial look indicates these warnings are not being exposed by `closure-compiler-npm`.

**Comment by kristoferbaxter** [comment]
Opened a separate issue for the "wish list" item which will require parsing the output of CC warnings.
