### ISSUE TITLE
Support "es" output format

### ISSUE THREAD

**Issue by guybedford** [ampproject/rollup-plugin-closure-compiler#5]
Would be great to get this one going :)

**Comment by kristoferbaxter** [comment]
Great idea. There is already minimal support if you don't need to export anything.

https://github.com/ampproject/rollup-plugin-closure-compiler/blob/master/test/rollup-config-to-flags.js#L42

Will investigate more thorough support.

**Comment by kristoferbaxter** [comment]
Started a [branch](https://github.com/ampproject/rollup-plugin-closure-compiler/tree/esmodules).

Outlined thoughts on how to support es module output format with [this scratchpad](https://github.com/ampproject/rollup-plugin-closure-compiler/blob/esmodules/src/scratchpad.md)

**Comment by kristoferbaxter** [comment]
@guybedford – Ran into a small issue, Rollup doesn't pass `OutputOptions` to the `transform` hook. This means transforms cannot be performed only for specific output formats.

Was considering switching to the following approach:
1. `transformChunk` => Modify source code as needed for Closure Compiler.
2. `generateBundle` => Run Closure Compiler on source, then run second pass removing source code changes to support Closure Compiler

Is this issue (Rollup doesn't pass OutputOptions to `transform` hooks) intended?

**Comment by kristoferbaxter** [comment]
Closed with #8.

**Comment by guybedford** [comment]
Amazing work. transformChunk is definitely the right approach.
