### ISSUE TITLE
Closure compiler artifacts left in the minified bundle

### ISSUE THREAD

**Issue by Andarist** [ampproject/rollup-plugin-closure-compiler#56]
Repro can be found in [this PR](https://github.com/facebook/react/pull/13321), you can check out complete output in my comment [here](https://github.com/facebook/react/pull/13321#issuecomment-420241486).

Basically what I see are things like some kind of scope object gathering properties like
- ASSUME_ES5
- ASSUME_NO_NATIVE_MAP
- ASSUME_NO_NATIVE_SET
- getGlobal
- SYMBOL_PREFIX
- initSymbol
- Symbol
- ... and others.

I understand that this can be disabled with `language_out: 'ECMASCRIPT_2015'`, but I'm wondering why this is not added in CJS case but is added for ESM? Could this be prevented altogether in the plugin itself? Without adding extra config like the mentioned `language_out`?

cc @TrySound

**Comment by kristoferbaxter** [comment]
Taking a look at this. Will respond back by EOD tomorrow with changes or a clarification.

**Comment by Andarist** [comment]
I'll try to extract one in following days.

**Comment by Andarist** [comment]
Here you go - https://github.com/Andarist/rollup-closure-symbol-repro

Couldn't repro it for a while because changing a function declaration to an arrow function expression causes the "polyfill bloat" to be added to both, keeping it as function declaration doesn't add the bloat to cjs output but adds it to esm.

**Comment by kristoferbaxter** [comment]
Taking a look. Thank you so much!

**Comment by kristoferbaxter** [comment]
The issue for this particular example appears to be in transpilation of the `export`, which isn't removed (but we do add a statement to ensure the name isn't mangled so the export can be repaired after Closure Compiler is finished).

Going to remove the export statements, and try to resolve.

**Comment by kristoferbaxter** [comment]
Released `0.7.0` with the change. However, NPM went down right afterwards.

**Comment by kristoferbaxter** [comment]
Confirmed fixed with `0.7.1`.

**Comment by TrySound** [comment]
Great job! Thanks

**Comment by Andarist** [comment]
Cool! Thanks
